=== VKaminski/online_market_vkaminski/controller-module/src/main/resources/items.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">

    <xs:element name="items" type="items"/>

    <xs:complexType name="items">
        <xs:sequence>
            <xs:element name="item" type="item" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="item">
        <xs:all>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="unique_number" type="xs:string"/>
            <xs:element name="price" type="xs:decimal"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== VKaminski/online_market_vkaminski/items.xml
<?xml version="1.0"?>
<items xmlns="http://www.it-academy.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.it-academy.by controller-module/src/main/resources/items.xsd">

    <item>
        <id>1</id>
        <name>LG</name>
        <description>Washing machine</description>
        <unique_number>temp1</unique_number>
        <price>150</price>
    </item>
    <item>
        <id>2</id>
        <name>Samsung</name>
        <description>Frize</description>
        <unique_number>temp2</unique_number>
        <price>500</price>
    </item>
    <item>
        <id>3</id>
        <name>Nokia</name>
        <description>Mobile phone</description>
        <unique_number>temp5</unique_number>
        <price>350</price>
    </item>
    <item>
        <id>4</id>
        <name>Nokia</name>
        <description>Mobile phone</description>
        <unique_number>temp4</unique_number>
        <price>370</price>
    </item>
    <item>
        <id>5</id>
        <name>Nokia</name>
        <description>Mobile phone</description>
        <unique_number>temp6</unique_number>
        <price>370</price>
    </item>
</items>
